
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: wazi-devspaces-{{ .Values.namespace }}  
  namespace: {{ .Values.namespace }} 
spec:
  auth:
    externalIdentityProvider: false
    initialOpenShiftOAuthUser: false
  database:
    externalDb: false
  metrics:
    enable: true
  server:
    cheFlavor: codeready
    allowUserDefinedWorkspaceNamespaces: false
    gitSelfSignedCert: false
    tlsSupport: true
    workspaceNamespaceDefault: wazi-devspaces-<username>
  storage:
    preCreateSubPaths: true
    pvcClaimSize: 10Gi
    postgresPVCStorageClassName: ibmc-vpc-block-10iops-tier
    pvcStrategy: per-workspace
    workspacePVCStorageClassName: ibmc-vpc-block-10iops-tier
